### ISSUE TITLE
Arxiv version or blog

### ISSUE THREAD

**Issue by joaogui1** [Gsunshine/Enjoy-Hamburger#2]
When are you going to release either the arxiv version or the blog?

**Comment by Gsunshine** [comment]
Many thanks for your attention!

We have released Chinese [blog 1](https://zhuanlan.zhihu.com/p/369769485) and [blog 2](https://zhuanlan.zhihu.com/p/369855045) and the incoming blog 3 on Zhihu. Need time to update the ArXiv version and English blog concerning the incoming NeurIPS deadline. 

I will try my best to release the ArXiv update in one week. 

Thanks again for your patience and interest!

**Comment by Gsunshine** [comment]
Plus, One-Step Gradient and some methods beyond work well for training implicit models like [MDEQ](https://github.com/locuslab/mdeq). One-Step Gradient is now theoretically sound! We have finished the theory part and ablation experiments and are currently working on the writings.  Again many writing works. Sorry for my late update.

We are also optimistic about further improving Hamburger via the newly proposed training mechanisms. We will release our new paper after the ArXiv update and the NeurIPS deadline.

**Comment by Gsunshine** [comment]
Hi,

Thanks for your waiting. I am writing this comment to update some progress.

The extension of One-Step Gradient, named Phantom Gradient, has set new state-of-the-art records for training previous SOTA implicit models MDEQ on CIFAR-10 and ImageNet while offering visible training time speedup. We provide theoretical guarantees on its optimization properties that also cover the One-Step Gradient as a special case. This paper has been submitted to NeurIPS 2021. 

Regarding the arXiv version of Hamburger, we add a short survey for implicit models, discuss why we treat the Hamburger as a semi-implicit model and list several important research problems related to this paper. It is more than the content scheduled before, especially the survey. So it can be more time-consuming.

I am particularly interested in the general properties that the operation $\mathcal{M}$ should have as a context module. Should we have a unified framework or the mathematical abstraction for this operation even beyond the MD's formulation in this paper? According to recent papers, it seems that the MD's formulation and the low-rankness is still only a subset of this family. A hypothesis is that it should be able to RESCALE the SPECTRUM of the representation. (Please see my Chinese blog 3 using Google Translation.) This is nearly the most significant problem raised in the arXiv version. Hence I hope to early reveal this question here to see if it is helpful to you.

We believe that some ideas in this paper match recent progress in our research community and are thus optimistic about the newly added parts. Though we cannot offer the manuscript now, we hope that this comment can help you clarify your questions. 

Thanks again for your long patience and interest. Feel free to email me if you have additional questions.

Best,
Zhengyang Geng

**Comment by Gsunshine** [comment]
Hi João,

Thank you very much for your waiting!

I have released the [arXiv](https://arxiv.org/abs/2109.04553) version. This version contains several potential topics for future works. I am also working on some of them. You may read it if you are interested. :)

I believe that there should be another update regarding the arXiv version in the following weeks, with more discussion concerning the implicit/semi-implicit perspective of Hamburger and its relation with DEQ models.

Plus, you can find me at [Twitter](https://twitter.com/ZhengyangGeng). I will release more info on Twitter. 

Cheers,
Zhengyang

**Comment by joaogui1** [comment]
Thank you for the ping!
