### ISSUE TITLE
Default process group has not been initialized

### ISSUE THREAD

**Issue by m828** [Gsunshine/Enjoy-Hamburger#7]
请问一下，我用train.sh能够将模型跑通，因为是单卡，GPUS=1，我想深入了解下模型的参数，想尝试debug，但是已经设置了--gpus 1，norm_cfg = dict(type='BN', requires_grad=True)，仍然报错Default process group has not been initialized, please make sure to call init_process_group.请问有什么办法解决吗？

**Comment by Gsunshine** [comment]
[seg](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg)这个目录是很久之前的code， 已经1年半没有维护过了。如果你现阶段想跑，我推荐用基于MMSeg的[**seg_light_ham**](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg_light_ham)跑，可以结合[VAN](https://github.com/Visual-Attention-Network)作为backbone。性能很强，可见2022.03.26的更新。

使用[**seg_light_ham**](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg_light_ham)，你可以选VAN-Tiny或者VAN-Small作为backbone，Ham或者Light-Ham作为[head](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/mmseg/models/decode_heads/ham_head.py)，在ADE20K数据集上跑。我觉得有希望能fit进1张卡，尤其是**Light-Ham**，非常轻量级。注意这个目录下的[dist_train.sh](https://github.com/Gsunshine/Enjoy-Hamburger/blob/main/seg_light_ham/dist_train.sh)的DDP是允许单卡跑的（印象中是），指定GPU数为1即可，应该也不需要修改norm_cfg，SyncBN可以支持单卡。如果单卡memory不太够，可以在[config](https://github.com/Gsunshine/Enjoy-Hamburger/blob/4a5b452f676af5e645f2a3068bd57df5d1c469de/seg_light_ham/configs/_base_/models/ham_van.py#L9)尝试修改把总的output stride从8改到16，这会进一步缩小训练的memory开销。

如果使用[seg](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg)这套旧code，我记得PASCAL VOC数据集上一个单卡可复现且速度比较快的setting。你可以用ResNet 50，stride 16，batch size 12，30K iterations来做ablation。这个是单卡11G用[seg](https://github.com/Gsunshine/Enjoy-Hamburger/tree/main/seg)这个目录可以跑的。我建议在这个setting下跑3~4组，用average+best来衡量在ham之上做进一步的修改是否有效。

应该是在settings.py里面设置
RUN_FOR_TEST = False
TRAIN_BATCH_SIZE = 12
ITER_MAX  = 30000
N_LAYERS = 50
STRIDE = 16

可以加assets里面的[Wechat](可以加assets里面的Wechat)，有问题欢迎继续问！

**Comment by m828** [comment]
> 

我是用的seg_light_ham，选择的是van_base。
我的意思是能够用dist_train.sh，gpus=1跑通，而且在我自己的数据集上第一次就达到了82.5mIoU，这是很好的结果。
所以对于该模型，我想深入学习下，想通过使用train.py的命令而不是.sh（因为train.py能够一步一步debug），但是一直报错Default process group has not been initialized, please make sure to call init_process_group.

**Comment by Gsunshine** [comment]
OK我理解你的问题了。我发现了下面几个链接跟你的问题相关：
https://github.com/facebookresearch/detectron2/issues/3972
https://github.com/pytorch/pytorch/issues/63662
https://github.com/open-mmlab/mmsegmentation/pull/772

看样子pytorch尚未支持单卡下DDP+SyncBN的训练，MMSeg选择在这种情况下把SyncBN换回BN，见[code](https://github.com/Gsunshine/Enjoy-Hamburger/blob/4a5b452f676af5e645f2a3068bd57df5d1c469de/seg_light_ham/train.py#L206)。所以我的理解是，是不是应该直接在train.py里面手动设置distributed为False，或者激活该变量为False，见此处[code](https://github.com/Gsunshine/Enjoy-Hamburger/blob/4a5b452f676af5e645f2a3068bd57df5d1c469de/seg_light_ham/train.py#L149)。可以尝试一下。

我使用的是seg_light_ham/train.py而非进一步的tools下面的seg_light_ham/tools/train.py。

感谢你的兴趣！希望能帮到你！

**Comment by m828** [comment]
> 

感谢您的细心解答！！！我会继续尝试下
